# -*- coding: utf-8 -*-
"""synapsef.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fbiXRarao3Mbmso5evN8JdN5y3_iL6fw
"""

def example_add(a, b):
  result = a + b
  return result