# -*- coding: utf-8 -*-
"""Sample3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L-p6-eWWRTzXNeXJDQIE-grrme9wlMfR
"""

import tensorflow as tf
from keras.layers import Dense, Input

class MyModel(tf.keras.Model):
    def __init__(self):
        super(MyModel, self).__init__()
        self.l1 = Dense(8, activation='tanh')
        self.l2 = Dense(10, activation='tanh')
        self.l3 = Dense(10, activation='tanh')
        self.l4 = Dense(1, activation='sigmoid')
    def call(self, inputs):
        x1 = self.l1(inputs)
        x2 = self.l2(x1)
        x3 = self.l3(x2)
        x4 = self.l4(x3)
        return x4

model = MyModel()