# -*- coding: utf-8 -*-
"""Copy of SyedSynapseCh3Session09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fogreapufE_pay4A7uKc_yS5Fp90FN8A
"""

(lambda x : x ** 2)(3)

a = lambda x : x ** 2
a(3)

get_pi = lambda : 3.14
get_pi()

a = lambda x, y : x + y
a(1, 2)

# Multi-line lambda using a trick with a list or tuple
# This isn't a true multi-line lambda, but a common workaround
process_data = lambda x: [
    print(f"Processing: {x}"),
    x * 2
][1] # Access the result from the list

result = process_data(5)
print(f"Result: {result}")

# Another way to simulate multiple steps
process_data_tuple = lambda x: (
    print(f"Processing with tuple: {x}"),
    x + 10
)[1]

result_tuple = process_data_tuple(7)
print(f"Result from tuple: {result_tuple}")

number = lambda x: "positive" if x>0 else 'negative' if x<0 else 'zero'
number(5)

power = lambda x, n=2: x ** n
power(7)

power(3, 3)

number = [1, 2, 3, 4, 5]
squared = list(map(lambda x: x ** 2, number))
squared

number = [1,2,3,4, 5,6,7,8,9,10]
even_numbers = list(filter(lambda x: x % 2 == 0, number))
even_numbers

#  Reduce shrink it and return result
# Reduce is available through functools library
# function calling
from functools import reduce
numbers = [1,2,3,4,5]
sum_of = reduce(lambda x, y: x + y, numbers)
sum_of

help(reduce)

def example_1():
  return lambda x : x * 3

a = example_1()
print(a(7))

class Person:
    def __init__(self, name, age):
        self.__name__ = name
        self.__age__ = age

    def introduce(self):
        return f"I am {self.__name__} and, I am {self.__age__} years old"
    def have_birthday(self):
        self.__age__ += 1
        return f"Happy {self.__age__}th birthday, {self.__name__}!"

# Example usage:
person1 = Person("Alice", 30)
print(person1.introduce())
print(person1.have_birthday())